# Generated by Django 5.1.6 on 2025-03-09 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('individual', 'Individual'), ('organization', 'Organization')], default='individual', max_length=20)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'main_users',
            },
        ),
        migrations.CreateModel(
            name='OffsetProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Tree Plantation', 'Tree Plantation'), ('Waste Management', 'Waste Management'), ('Solar Management', 'Solar Management'), ('Rainwater Harvesting', 'Rainwater Harvesting'), ('Biogas Projects', 'Biogas Projects'), ('E-Waste Recycling', 'E-Waste Recycling'), ('Plastic Waste Reduction', 'Plastic Waste Reduction'), ('Afforestation Projects', 'Afforestation Projects'), ('Community Solar Projects', 'Community Solar Projects'), ('Eco Brick Projects', 'Eco Brick Projects')], default='Tree Plantation', max_length=100)),
                ('location', models.CharField(default='Unknown', max_length=200)),
                ('target_amount', models.IntegerField()),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('contact_email', models.EmailField(max_length=254)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'offset_project',
            },
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('project_name', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('payment_mode', models.CharField(default='UPI', max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contribution',
            },
        ),
    ]
