# Generated by Django 5.1.6 on 2025-02-28 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OffsetProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Tree Plantation', 'Tree Plantation'), ('Solar Energy', 'Solar Energy'), ('Waste Management', 'Waste Management')], default='Tree Plantation', max_length=100)),
                ('location', models.CharField(default='Unknown', max_length=200)),
                ('target_amount', models.IntegerField()),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('contact_email', models.EmailField(max_length=254)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'offset_project',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('individual', 'Individual'), ('organization', 'Organization')], max_length=20)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'main_users',
            },
        ),
    ]
