# Generated by Django 5.1.6 on 2025-03-07 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offsetproject',
            name='category',
            field=models.CharField(choices=[('Tree Plantation', 'Tree Plantation'), ('Waste Management', 'Waste Management'), ('Solar Management', 'Solar Management'), ('Rainwater Harvesting', 'Rainwater Harvesting'), ('Biogas Projects', 'Biogas Projects'), ('E-Waste Recycling', 'E-Waste Recycling'), ('Plastic Waste Reduction', 'Plastic Waste Reduction'), ('Afforestation Projects', 'Afforestation Projects'), ('Community Solar Projects', 'Community Solar Projects'), ('Eco Brick Projects', 'Eco Brick Projects')], default='Tree Plantation', max_length=100),
        ),
    ]
