# Generated by Django 5.1.6 on 2025-03-09 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_users_date_joined_users_first_name_users_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='users',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='users',
            name='last_name',
        ),
    ]
