# Generated by Django 5.1.6 on 2025-03-08 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_users_managers_remove_users_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_superuser',
        ),
    ]
